# Generated by Django 3.1.4 on 2020-12-12 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 7, 53, 11, 429282)),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(),
        ),
    ]
