# Generated by Django 3.1.4 on 2020-12-12 08:04

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_auto_20201212_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 8, 4, 58, 86326)),
        ),
    ]
