# Generated by Django 3.1.4 on 2020-12-12 08:05

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_auto_20201212_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 8, 5, 51, 487432)),
        ),
    ]
