# Generated by Django 3.1.4 on 2020-12-12 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_auto_20201212_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 8, 16, 6, 8814)),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(choices=[('1', '2'), ('3', '4')]),
        ),
    ]
