# Generated by Django 3.1.4 on 2020-12-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0012_auto_20201212_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time2',
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 9, 2, 37, 119754)),
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.TimeField(),
        ),
    ]
