# Generated by Django 3.1.4 on 2021-01-10 19:31

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_auto_20201212_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=colorfield.fields.ColorField(default='#ccc', max_length=18),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 22, 31, 15, 345033)),
        ),
    ]
