# Generated by Django 3.1.4 on 2021-01-11 11:15

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_auto_20210110_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 11, 14, 15, 15, 328905)),
        ),
    ]
